FROM alpine:3.19

ENV ADMINER_URL="https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php"

RUN apk update && apk add wget=1.21.4-r0 && apk add php && apk add php83=8.3.8-r0 && apk add php83-session=8.3.8-r0 && apk add php83-mbstring=8.3.8-r0 && \
	apk add php83-mysqli=8.3.8-r0 && apk add php83-pdo_mysql=8.3.8-r0 && apk add dumb-init=1.2.5-r3

RUN mkdir -p /var/lib/adminer && wget -qO /var/lib/adminer/index.php ${ADMINER_URL}

COPY ./tools ./tools

RUN chmod +rwx ./tools/adminer.sh
RUN ln -s /usr/bin/php83 /usr/bin/php

EXPOSE 8080

ENTRYPOINT ["./tools/adminer.sh"]
