FROM alpine:3.19

RUN apk update && apk add php83=8.3.8-r0 && apk add php83-fpm=8.3.8-r0 && apk add php83-mysqli=8.3.8-r0 && apk add php83-phar=8.3.8-r0 && \
	apk add php83-mbstring=8.3.8-r0 && apk add php83-tokenizer=8.3.8-r0 && apk add php83-pecl-redis=6.0.2-r0 && apk add php83-ctype=8.3.8-r0 && \
	apk add curl=8.5.0-r0 && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY ./conf/www.conf /etc/php83/php-fpm.d/www.conf
COPY ./tools ./tools

RUN chmod +rwx ./tools/wordpress.sh
RUN ln -s /usr/bin/php83 /usr/bin/php
EXPOSE 9000

ENTRYPOINT ["./tools/wordpress.sh"]
