FROM alpine:3.19

RUN apk update && apk add nginx=1.24.0-r16 && apk add openssl=3.1.5-r0

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

COPY ./conf/http.d /etc/nginx/http.d

COPY ./tools /etc/nginx/tools

RUN chmod +rwx /etc/nginx/tools/nginx.sh

RUN mkdir /etc/nginx/ssl

EXPOSE 443

ENTRYPOINT ["/etc/nginx/tools/nginx.sh"]
