FROM alpine:3.19

RUN apk update && apk add redis=7.2.4-r0

RUN sed -i 's/protected-mode yes/protected-mode no/' /etc/redis.conf
RUN sed -i 's/bind 127.0.0.1 -::1/bind * -::*/' /etc/redis.conf

EXPOSE 6379

ENTRYPOINT ["redis-server", "/etc/redis.conf"]
